### ISSUE TITLE
Contact Us Form - Floodchecking

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Hallowspeak#16]
**Is your feature request related to a problem? Please describe.**
Technically speaking, someone could currently put a bot to the contact-us form and spam our discord channel. So we should floodcheck it somehow

**Describe the solution you'd like**
Either have some form of captcha, but even better just time someone out for maybe 30-60 seconds after sending (could be stored in a cookie)

**Additional context**
If we're using cookies we probably should have a consent checkbox at the form that we'll be storing a cookie for X amount of time _🙄 @ GDPR_

**Comment by justjustie** [comment]
A cookie could technically be circumvented, we could blacklist the client's ip for a minute alternatively
