### ISSUE TITLE
Custom font not loading on mobile

### ISSUE THREAD

**Issue by justjustie** [dylanpiera/Hallowspeak#7]
**Describe the bug**
Perpetua font not displaying correctly on mobiloe

**To Reproduce**
Open the page on a smartphone

**Expected behavior**
The font (Perpetua) loads and displays correctly

**Screenshots**
![grafik](https://user-images.githubusercontent.com/20815155/65463417-f8d8f580-de57-11e9-971d-5267ebc40891.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10
 - Browser: Chrome
 - Version: 77.0.3865.92

**Additional context**
Not really testable since local build server to localhost

**Comment by dylanpiera** [comment]
Can reproduce on Oneplus 5T - Android 9
![Screenshot_20190924-075518](https://user-images.githubusercontent.com/2012848/65485000-dd460d00-dea0-11e9-86c1-5383326208d7.jpg)

**Comment by justjustie** [comment]
Already have an idea, PR coming later
